#Change to version 3 to use kompose 1.5
version: '3.1'
services:
  vessel-service:
    build:
      context: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
  user-service:
    build:
      context: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICOR_REGISTRY : "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
  datastore:
    image: mongo
    ports:
      - 27017:27017
  database:
    image: postgres
    ports:
      - 5432:5432
  consignment-cli:
      build:
        context: ./consignment-cli
      environment:
        MICRO_REGISTRY: "mdns"
  consignment-service:
    build:
      context: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
  user-cli:
    build:
      context: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"