apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f .\docker-compose.yml
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: consignment-service
  name: consignment-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: consignment-service
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: datastore:27017
        - name: MICRO_ADDRESS
          value: :50051
        - name: MICRO_REGISTRY
          value: mdns
        image: consignment-service
        name: consignment-service
        #Use local image
        imagePullPolicy: Never
        ports:
        - containerPort: 50051
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose.yml
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: consignment-service
  name: consignment-service
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
  selector:
    io.kompose.service: consignment-service
status:
  loadBalancer: {}

